# Generated by Django 4.2.15 on 2024-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_patientmedicalreportmodel_custom_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvistormodel',
            name='visitor_pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_alias_name',
            field=models.CharField(blank=True, choices=[('0', 'פקיד'), ('2', 'طبيب'), ('3', 'לבורנט')], max_length=255, null=True, verbose_name='اسم المستعار للملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'זכר'), ('2', 'נקבה')], max_length=255, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('0', 'מנהל'), ('2', 'פקיד'), ('3', 'מטופל')], max_length=255, null=True, verbose_name='نوع الملف الشخصي'),
        ),
    ]
