# Generated by Django 4.2.15 on 2024-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_patientvistormodel_visitor_pay_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvistormodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
