# Generated by Django 4.2.15 on 2024-09-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_patientmedicalreportmodel_oxygen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='oxygen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='pulse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalreportmodel',
            name='sugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
